### ISSUE TITLE
TinyMCE Buttons disappear upon activation of Plugin in WP

### ISSUE THREAD

**Issue by stomosvary** [jeherve/WP-Facebook-applications#3]
After troubleshooting this issue on my original site, I installed a brand new version of WordPress and upon activation of this plugin, the TinyMCE buttons disappear in the visual editor.

Disabling the plugin doesn't resolve the issue either so I assume there is some database change that occurs.
Can you advise me how to restore my TinyMCE buttons?

**Comment by jeherve** [comment]
Which version of the plugin and of WordPress are you using? I am having issues trying to reproduce the issue on my machine.

Nothing in the plugin is related to TunyMCE so I am curious how this could happen.

**Comment by stomosvary** [comment]
WP 3.2.1 & Version 0.3.1 - I also tried updating to version .4 from the GitHub source but it didn't help.
I can e-mail you login details to my WP install if you want.

**Comment by jeherve** [comment]
Alright. I have googled around a bit and found [a similar issue with another plugin](http://wordpress.org/support/topic/tinymce-toolbar-disappears?replies=23). It happened with WordPress instances where the directory wp-content/ had been renamd into something else. is that your case?

**Comment by stomosvary** [comment]
No the file/directory structure is normal.

**Comment by stomosvary** [comment]
If I do a vanilla install the issue occurs when I activate the plugin.  I have not run into any issues similar to this previously and would expect that deactivating the plugin would solve the problem but it doesn't so I am really baffled as to what exactly is happening.

**Comment by jeherve** [comment]
Could you try again, with the latest version of the plugin available [here](https://github.com/jeherve/WP-Facebook-applications/zipball/master) ?. Not sure it is going to fix the problem, but if it does, I will push that version to the WordPress repo as well.

Related commit: a5f69a976a03e89a5d77fb28fc3f503553c6002f
